# templates/mysql/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc }}
{{- range .Values.teams }}
  {{ .name }}-mysql-password: {{ .mysql.password | b64enc }}
{{- end }}
