# templates/storage/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: shared-db-services
    meta.helm.sh/release-namespace: shared-services
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer