# templates/redis/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range .Values.teams }}
  {{ .name }}-redis-password: {{ .redis.password | b64enc }}
  {{- end }}